# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2ebc3e6378343172b0c6dfd858f11352064cafb907ca7e00793362cb1df1a10d9ada076b5e7b69b8e6f1c8990e50e2fa8d22a02a253b939f8ac93d3c12adc88

test:
  secret_key_base: 91829eeb9cbacd8a204cddae73f7f29c077dbacb6eae70cfc8162674953b143fb38e07b1fc54661d6511b887b473c360451a8cc84bd67d1d880bd67cce668156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
